---- PL/SQL -----
SET SERVEROUTPUT ON;

BEGIN
    DBMS_OUTPUT.PUT_LINE('HELLO');
END;
/
--한 덩어리의 프로시저
DECLARE --변수 선언
    EMP_ID  NUMBER;
    EMP_NAME    VARCHAR2(30);
BEGIN
    EMP_ID := 888; -- := 대입,= 같은지 비교
    EMP_NAME:='배장남';
    
    DBMS_OUTPUT.PUT_LINE('아이디:' ||EMP_ID);
    DBMS_OUTPUT.PUT_LINE(EMP_NAME);
END;
/

DECLARE
EMP_ID EMP.EMPNO%TYPE;
EMP_NAME EMP.ENAME%TYPE;
BEGIN
SELECT EMPNO, ENAME
INTO EMP_ID, EMP_NAME
FROM EMP
WHERE EMPNO = '&EMP_ID';
DBMS_OUTPUT.PUT_LINE('EMP_ID : ' || EMP_ID);
DBMS_OUTPUT.PUT_LINE('EMP_NAME : ' || EMP_NAME);
END;
/

DECLARE
    E   EMP%ROWTYPE; --행들의 타입을 하나로 모아서 사용가능
BEGIN
SELECT *
INTO E
FROM EMP
WHERE EMPNO='&EMP_ID';
DBMS_OUTPUT.PUT_LINE('EMP NO : ' || E.EMPNO);
DBMS_OUTPUT.PUT_LINE('EMP JOB : ' || EMP.JOB);
END;
/
CREATE OR REPLACE PROCEDURE PROC_FIND_EMP_INFO
IS    -->DECLARE 대신 써주고 밑에는 동일하게 사용.
--DECLARE  
    EMP_ID EMP.EMPNO%TYPE;
    EMP_NAME EMP.ENAME%TYPE;
    SALARY EMP.SAL%TYPE;
    BONUS EMP.COMM%TYPE;
BEGIN
    SELECT EMPNO,ENAME,SAL,NVL(COMM,0)
    INTO EMP_ID,EMP_NAME,SALARY,BONUS
    FROM EMP
    WHERE EMPNO = '&EMPNO';
    
    IF(BONUS=0)
        THEN DBMS_OUTPUT.PUT_LINE('보너스를 지급받지 않는 사원입니다');
    ELSIF(BONUS=300)
        THEN DBMS_OUTPUT.PUT_LINE('와우 보너스 300받는 사원입니다');
    ELSE
         DBMS_OUTPUT.PUT_LINE('보너스율:'||BONUS *100 || '%');
        END IF;
        FOR N IN REVERSE 10..13 LOOP
        DBMS_OUTPUT.PUT_LINE(N);
        END LOOP;
EXCEPTION
    WHEN NO_DATA_FOUND
        THEN  DBMS_OUTPUT.PUT_LINE('사원을 찾지 못했어요');
END;
/

--객체 PROCEDUER, FUNCTION : 코드를 찾아서 실행하는 불편함을 줄인다. 호출해서 사용.
--TRIGGER,CURSOR,PACKGAE


--아몰랑,,,,
CREATE OR REPLACE PROCEDURE PROC_FIND_EMP_WITH_VAR
    (VENO IN EMP.EMPNO%TYPE,      --매개변수
     VENAME OUT EMP.ENAME%TYPE,
     VSAL OUT EMP.SAL%TYPE,
     VCOMM OUT EMP.COMM%TYPE,
     MSG OUT VARCHAR2)
IS
BEGIN
    SELECT EMPNO,ENAME,SAL,NVL(COMM,0)
    INTO VENO,VENAME,VSAL,COMM
    FROM EMP
    WHERE EMPNO = VENO;
    
    IF(VCOMM=0)
        THEN DBMS_OUTPUT.PUT_LINE('보너스를 지급받지 않는 사원입니다');
         MSG:='보너스를 지급받지않는 사원입니다'; 
    ELSIF(VCOMM=300)
        THEN DBMS_OUTPUT.PUT_LINE('와우 보너스 300받는 사원입니다');
        MSG:='보너스를 300 사원입니다';    
    ELSE
         DBMS_OUTPUT.PUT_LINE('보너스율:'||BONUS *100 || '%');
         MSG:='ㄹㄴㅇㄹㅇㅁㄴㄹ';
        END IF;
        
EXCEPTION
    WHEN NO_DATA_FOUND
        THEN  DBMS_OUTPUT.PUT_LINE('사원을 찾지 못했어요');
END;
/
SET AUTOPRINT ON;
VARIABLE VAR_ENAME VARCHAR2(10);
VARIABLE VAR_SAL NUMBER;
VARIABLE VAR_COMM NUMBER;
VARIABLE VAR_MSG VARCHAR2(150);
EXEC PROC_FIND_WITH_VAR
    (7788,
        :VAR_ENAME,
        :VAR_SAL,
        :VAR_COMM,
        :VAR_MSG    );
PRINT VAR_ENAME;
PRINT VAR_SAL;
PRINT VAR_COMM;
PRINT VAR_MSG;


